version: '3.7'

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=team_clueless
      - POSTGRES_PASSWORD=team_clueless
      - POSTGRES_DB=team_clueless_prod
    networks:
      - my-net

  redis-master:
    image: 'bitnami/redis:latest'
    restart: always
    user: root
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    networks:
      - my-net

  redis-replica:
    image: 'bitnami/redis:latest'
    restart: always
    user: root
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_replica_password
    depends_on:
      - redis-master
    networks:
      - my-net

  web:
    build:
      context: ./services/web
      dockerfile: ./Dockerfile.prod
    restart: always
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://team_clueless:team_clueless@db:5432/team_clueless_prod
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - APP_FOLDER=/home/app/web
      - SESSION_TYPE=redis
      - SESSION_REDIS=redis://myredis:6379
    depends_on:
      - db
      - redis-master
      - redis-replica
    networks:
      - my-net

  nginx:
    #image: nginx:latest
    build: ./services/nginx
    restart: always
    volumes:
      #- $HOME/project/services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 8080:80
    depends_on:
      - web
    networks:
      - my-net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my-net:
    driver: bridge
