version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: ./Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://team_clueless:team_clueless@db:5432/team_clueless_prod
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - APP_FOLDER=/home/app/web
    depends_on:
      - db
    networks:
      - my-net

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=team_clueless
      - POSTGRES_PASSWORD=team_clueless
      - POSTGRES_DB=team_clueless_prod
    networks:
      - my-net

  nginx:
    build: nginx:latest
    volumes:
      - $HOME/services/nginx:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 8080:80
    depends_on:
      - web
    networks:
      - my-net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my-net:
    driver: bridge
